WIP: Map in problem details
vilnius/tvarkau-vilniu pull request #117
Opened 2016-12-04 17:26 UTC by vycius

2016-12-04 18:24 UTC, mjurkus requested changes

2016-12-04 18:24 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/fragments/ProblemDetailFragment.kt
> +                            problem_images_view_pager_indicator.gone()
Can use `goneIf()` extension

2016-12-04 18:24 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +    override fun isViewFromObject(view: View, `object`: Any): Boolean {
`object` > `any`

2016-12-04 18:24 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +        return view === `object`
inline

2016-12-04 18:24 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +            if (problem_map_view != null) {
when `problem_map_view` could be null?

2016-12-04 18:24 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +                    it.run {
What is this additional `run` is for?

2016-12-04 18:24 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +                        moveCamera(CameraUpdateFactory.newLatLng(problem!!.latLng))
If someone were to remove if condition in `instantiateItem` this would throw exception. Suggest passing problem directly to this function.

2016-12-04 18:24 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +
empty line

2016-12-04 18:24 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +            problem_image_view.setOnClickListener { v ->
`v` is not used

2016-12-04 18:24 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +    constructor(context: Context, problem: Problem) : this(context, problem.photos.orEmpty()) {
I'd suggest using 2 adapters, since it now breaks SRP.

2016-12-06 19:15 UTC, vycius commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +    constructor(context: Context, problem: Problem) : this(context, problem.photos.orEmpty()) {
Now using two adapters

2016-12-06 21:08 UTC, mjurkus reviewed
Still I would suggest refactoring `ProblemImagesPagerAdapter` even further.
`ProblemImagesPagerAdapter` should not contain logic on what it should display.
Logic on wether it should show map or photo should be contained In fragment of activity where this adapter is used.
Because now adapter is still violating SRP. It's name even states that it displays `ProblemImages`

2016-12-06 21:08 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +            it.run {
Why do you use `run { }` here?

2016-12-06 21:08 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +        if (position == count - 1) {
Why + 1 at line 21 and - 1 here?

2016-12-06 21:11 UTC, vycius commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +        if (position == count - 1) {
+1 is for displaying map at the last image splot

2016-12-06 21:12 UTC, vycius commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +            it.run {
Why do you think `run { }` is misused here ?

2016-12-06 21:13 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/views/adapters/ProblemImagesPagerAdapter.kt
> +            it.run {
Because `run { }` does not provide any value.

2016-12-06 21:14 UTC, mjurkus commented
Nevermind that long comment about splitting adapter even further. From adapter's name I thought it is used to display photos OR map.

2016-12-06 21:16 UTC, vycius commented
Yup I think name `ProblemImagesPagerAdapter` is confusing, but I haven't come up with better name. It displays photos and lite map (like photo of the map). Do you have any suggestions for naming here ?

2016-12-06 21:21 UTC, inetaa commented
Regarding naming it was decided some time ago not to use _Problem_ at all because of negative aspect, instead please use _Report_.

2016-12-06 21:24 UTC, vycius commented
@inetaa we should do renaming in whole project. It will be really confusing if only in this adapter we will use report and in another places problem.

2016-12-06 21:35 UTC, mjurkus approved these changes

2016-12-06 21:42 UTC, merged