Show progress dialog on new report submit
vilnius/tvarkau-vilniu pull request #132
Opened 2016-12-18 15:52 UTC by mjurkus

2016-12-18 18:06 UTC, vycius commented
Got exception. 
```
 android.view.WindowLeaked: Activity lt.vilnius.tvarkau.activity.ReportRegistrationActivity has leaked window DecorView@eed145f[] that was originally added here
                                                                       at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
                                                                       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                       at android.app.Dialog.show(Dialog.java:322)
                                                                       at lt.vilnius.tvarkau.fragments.NewReportFragment.showProgress(NewReportFragment.kt:551)
                                                                       at lt.vilnius.tvarkau.mvp.presenters.NewReportPresenterImpl$submitProblem$3.call(NewReportPresenterImpl.kt:49)
                                                                       at rx.internal.operators.SingleDoOnSubscribe.call(SingleDoOnSubscribe.java:43)
                                                                       at rx.internal.operators.SingleDoOnSubscribe.call(SingleDoOnSubscribe.java:28)
                                                                       at rx.internal.operators.SingleDoOnUnsubscribe.call(SingleDoOnUnsubscribe.java:42)
                                                                       at rx.internal.operators.SingleDoOnUnsubscribe.call(SingleDoOnUnsubscribe.java:28)
                                                                       at rx.Single.subscribe(Single.java:1876)
                                                                       at rx.Single.subscribe(Single.java:1686)
                                                                       at lt.vilnius.tvarkau.mvp.presenters.NewReportPresenterImpl.submitProblem(NewReportPresenterImpl.kt:51)
                                                                       at lt.vilnius.tvarkau.fragments.NewReportFragment.onOptionsItemSelected(NewReportFragment.kt:160)
                                                                       at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2212)
                                                                       at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2295)
                                                                       at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:353)
                                                                       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:414)
                                                                       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:198)
                                                                       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:107)
                                                                       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:107)
                                                                       at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
                                                                       at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
                                                                       at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:777)
                                                                       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:817)
                                                                       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                                       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:964)
                                                                       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:954)
                                                                       at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
                                                                       at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:157)
                                                                       at android.view.View.performClick(View.java:5637)
                                                                       at android.view.View$PerformClick.run(View.java:22429)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
Scenario: click submit, select location, click submit.

2016-12-18 18:14 UTC, vycius requested changes
Good work, but please investigate WindowLeaked.

2016-12-18 18:14 UTC, vycius commented on app/src/main/java/lt/vilnius/tvarkau/fragments/NewReportFragment.kt
> +        progressDialog?.show()
Can `progressDialog` be null at this place ?

2016-12-18 18:21 UTC, vycius commented
IMHO I think the problem is that you are using `progressDialog::hide` instead of `progressDialog::dismiss`

2016-12-18 19:04 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/fragments/NewReportFragment.kt
> +        progressDialog?.show()
KT can't now it this property wasn't modified in another thread.
So it's either `!!` or `?`

2016-12-18 20:04 UTC, mjurkus commented
Updated

2016-12-19 08:02 UTC, vycius commented on app/src/main/java/lt/vilnius/tvarkau/fragments/NewReportFragment.kt
>      override fun onDestroyView() {
Use `progressDialog::dismiss` in `onDestroyView`.

2016-12-19 08:21 UTC, vycius approved these changes
Use `progressDialog::dismiss` in `onDestroyView`, because leak might happen with current implementation. After that feel free to merge.

2016-12-19 08:24 UTC, vycius commented on app/src/main/java/lt/vilnius/tvarkau/fragments/NewReportFragment.kt
>      override fun onDestroyView() {
Also there is no need to set it to null `progressDialog = null` if you are using `progressDialog::dismiss`

2016-12-19 13:39 UTC, vycius approved these changes

2016-12-19 13:56 UTC, merged