Fill date time field with exif date time if possible
vilnius/tvarkau-vilniu pull request #138
Opened 2016-12-21 08:40 UTC by mjurkus

Reference: https://trello.com/c/4CWUGCU8/158-add-options-to-insert-info-into-date-time-field

2016-12-21 08:46 UTC, vycius requested changes

2016-12-21 08:46 UTC, vycius commented on app/src/main/java/lt/vilnius/tvarkau/utils/FormatUtils.java
> +    public static String formatExifAsLocalDateTime(@NonNull String exifDateTime) {
Make this method to return null on exception. From function definition we don't know if it can throw an exception.

2016-12-21 08:52 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/utils/FormatUtils.java
> +    public static String formatExifAsLocalDateTime(@NonNull String exifDateTime) {
Then maybe always null?

2016-12-21 08:56 UTC, vycius commented on app/src/main/java/lt/vilnius/tvarkau/utils/FormatUtils.java
> +    public static String formatExifAsLocalDateTime(@NonNull String exifDateTime) {
Why always ? I see no reason to have try/catch in `NewReportFragment.kt` just because this function might throw exception.

2016-12-21 08:58 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/utils/FormatUtils.java
> +    public static String formatExifAsLocalDateTime(@NonNull String exifDateTime) {
I mean try/catch in `formatExifAsLocalDateTime` and on error return null

2016-12-21 09:00 UTC, vycius commented on app/src/main/java/lt/vilnius/tvarkau/utils/FormatUtils.java
> +    public static String formatExifAsLocalDateTime(@NonNull String exifDateTime) {
Yup. Just move `NewReportFragment.kt` try/catch to `formatExifAsLocalDateTime`.

2016-12-21 20:41 UTC, mjurkus commented
Updated

2016-12-22 14:37 UTC, vycius commented
I think one problem exists with this PR. If user selected date from calendar manually after selecting photo, date is overridden by photo EXIF date. In this case user should reselect date from calendar.

2016-12-22 14:44 UTC, mjurkus commented
@vycius we already discussed this with @RenatBuga. It should override any date already entered in that field.

2016-12-23 09:10 UTC, vycius approved these changes
LGTM

2016-12-23 09:11 UTC, merged