Cleanup for FullscreenImageActivity
vilnius/tvarkau-vilniu pull request #190
Opened 2017-03-24 11:43 UTC by rokasjasonas

2017-03-24 11:51 UTC, mjurkus commented
Care to convert to Kotlin?

2017-03-24 11:54 UTC, rokasjasonas commented
https://media.giphy.com/media/3o7abnZIGzKF8OjnEI/giphy.gif

2017-03-24 12:40 UTC, mjurkus requested changes

2017-03-24 12:40 UTC, mjurkus commented on app/src/main/java/lt/vilnius/tvarkau/FullscreenImageActivity.kt
> +    private var initialImagePosition: Int = 0
This approach works better - you can see where value is retrieved from:

```
private val initialImagePosition: Int
  get() = intent.getIntExtra(....)
```

Same with `photos`

2017-03-27 14:12 UTC, rokasjasonas commented
Requested changes done!

2017-03-27 14:14 UTC, mjurkus commented
Hmm. Something went very wrong here... Unnecessary commits were added to your PR. Please, rebase.

2017-11-27 07:45 UTC, ViliusKraujutis commented
@rokasjasonas ping

2018-05-14 08:23 UTC, vycius commented
Closing PR due to inactivity. @rokasjasonas Feel free to reopen it if you continue working on this.

2018-05-14 08:23 UTC, closed without merging